const en = {
    "Shipping Tracking": "Shipping Tracking",
    "Automate Shipping and Setup Costs": "Automatically calculate shipping and setup costs based on customer location to prevent mistakes at the time of order and save time.",
    "Theme": "Theme",
    "Customize Your Theme": "You can continue to use the system with the appearance you want by making your theme settings as you wish.",
    "Mobile": "Mobile",
    "No Installation Required": "Our system requires no installation and can be accessed instantly from any device.",
    "Domain Management": "Domain Management",
    "Store Your Domain": "Store your domain on your own servers or with Mobitolya.",
    "E Commerce Integration": "E-commerce Integration",
    "Instant Integration With E Commerce Platforms": "Instant integration with many e-commerce environments such as Woo-commerce, Trendyol.",
    "Sales": "Sales",
    "Manage Your Products From A Single Panel": "You will be able to manage your products, product prices, and your sales from a single panel.",
    "Sms/Mail Integration": "Sms/Mail Integration",
    "Send Special Offers To Your Customers": "Send special offers to your customers and sms/mail integration for many transactions.",
    "Maintenance and Security": "Maintenance and Security",
    "Your Data Is Stored Securely": "Your data is stored securely and backed up regularly every week.",
    "TransferCurrencyExchangeDescription":"Since the exchange rate between the two accounts is different, enter the amount to be transferred to the opposite account manually. If you do not enter, conversion will be made at the current exchange rate.",
    "transportationCode_info": "Transportation Code is a unique code that is used to track the transportation process of the product. It is generated automatically when the product is shipped.",
    'offerMessage': 'Click the link to see our great offer for selected products as {companyName} at /%23/Public/CustomerDeal/{code}',
    "Add new {item} option": "Add New {item} Option",
    "empty_text": "",
    "Set the percentage profit for this product. If no value is entered, the default rate is shown.": "Bu ürünün yüzde kaç karla satılacağını belirleyin. Bir değer girmezseniz varsayılan oran gösterilir.",
    "Add Service": "Add Service",
    "Add Product": "Add Product",
    "Edit Service": "Edit Service",
    "Edit Product": "Edit Product",
    "Save": "Save",
    "Name On Sale": "Name On Sale",
    "Selling Price": "Selling Price",
    "Promotional Price": "Promotional Price",
    "Product Code": "Product Code",
    "Currency Type": "Currency Type",
    "Is a Service": "Is a Service",
    "Own Provided Service": "Own Provided Service",
    "Own Production": "Own Production",
    "Operation": "Operation",
    "Production": "Production",
    "Supplier": "Supplier",
    "Name In Production": "Name In Production",
    "Purchase List Price": "Purchase List Price",
    "Purchase Price": "Purchase Price",
    "Cost": "Cost",
    "Tags": "Tags",
    "Category": "Category",
    "Discard": "Discard",
    "Publish": "Publish",
    "Drop or select a cover image": "Drop or select a cover image",
    "Percentage": "Percentage",
    "Deposit": "Deposit",
    "Withdrawal": "Withdrawal",
    "TRY": "TRY",
    "USD": "USD",
    "EUR": "EUR",
    "GBP": "GBP",
    "Ordered": "Ordered",
    "Canceled": "Canceled",
    "Preparing": "Preparing",
    "Depot": "Depot",
    "Transporting": "Transporting",
    "Completed": "Completed",
    "Refund": "Refund",
    "Customer": "Customer",
    "Transporter": "Transporter",
    "Textile": "Textile",
    "Other": "Other",
    "Expense": "Expense",
    "Revenue": "Revenue",
    "Debit": "Debit",
    "Credit": "Credit",
    "WaitingToCustomer": "Waiting To Customer",
    "Accepted": "Accepted",
    "Rejected": "Rejected",
    "Confirmed": "Confirmed",
    "CustomerWaitingForNewOffer": "Customer Waiting For New Offer",
    "Products": "Products",
    "Deals": "Deals",
    "SellingOrders": "Selling Orders",
    "BuyingOrders": "Buying Orders",
    "Accounts": "Accounts",
    "Payments": "Payments",
    "SupplierAccounting": "Supplier Accounting",
    "CustomerAccounting": "Customer Accounting",
    "Settings": "Settings",
    "SmsEmail": "SMS/Email",
    "Active": "Active",
    "Passive": "Passive",
    "None": "None",
    "Monthly": "Monthly",
    "Quarterly": "Quarterly",
    "Semiannually": "Semiannually",
    "Annually": "Annually",
    "OnlyIntegration": "Only Integration",
    "IntegrationAndSelling": "Integration and Selling",
    "All": "All",
    "Producted": "Producted",
    "NotStarted": "Not Started",
    "InProgress": "In Progress",
    "Admin": "Admin",
    "CompanyManager": "Company Manager",
    "SalesConsultant": "Sales Consultant",
    "SupportUser": "Support User",
    "ShipmentUser": "Shipment User",
    "AccountingUser": "Accounting User",
    "App": "App",
    "Home": "Home",
    "Orders": "Orders",
    "Offers": "Offers",
    "Customer Orders": "Customer Orders",
    "Supplier Orders": "Supplier Orders",
    "Invoices": "Invoices",
    "Accounting": "Accounting",
    "Cashs": "Cashs",
    "Financial Accounts": "Financial Accounts",
    "Financial Items": "Financial Items",
    "Financial Transactions": "Financial Transactions",
    "Financial Plans": "Financial Plans",
    "System": "System",
    "Company": "Company",
    "Users": "Users",
    "Roles": "Roles",
    "Product Name": "Product Name",
    "Status": "Status",
    "Manufacturer": "Manufacturer",
    "Stock Code": "Stock Code",
    "Stock Quantity": "Stock Quantity",
    "Product Purchase Price": "Product Purchase Price",
    "Product Selling Price": "Product Selling Price",
    "Discounted Selling Price": "Discounted Selling Price",
    "Last Update": "Last Update",
    "Actions": "Actions",
    "Filter": "Filter",
    "Profile successfully updated": "Profile successfully updated",
    "Succeeded": "Succeeded",
    "Password successfully updated": "Password successfully updated",
    "Password must be at least 6 characters long": "Password must be at least 6 characters long",
    "New password repeat not equal to new password": "New password repeat not equal to new password",
    "Error": "Error",
    "Email already using by another user": "Email already using by another user",
    "Enter a valid email address": "Enter a valid email address",
    "{field} field is required": "{field} field is required",
    "Options": "Options",
    "Filter Menu": "Filter Menu",
    "Clear": "Clear",
    "Create New": "Create New",
    "Keyword Search": "Keyword Search",
    "No data found": "No data found",
    "Loading data. Please wait": "Loading data. Please wait",
    "Create Date": "Create Date",
    "{totalRecords} records found from {first} to {last}": "{totalRecords} records found from {first} to {last}",
    "Search by Name": "Search by Name",
    "Search by Email": "Search by Email",
    "dd/mm/yyyy": "mm/dd/yyyy",
    "Edit": "Edit",
    "Delete": "Delete",
    "Add User": "Add User",
    "Edit User": "Edit User",
    "General": "General",
    "Name": "Name",
    "Phone Number": "Phone Number",
    "User Type": "User Type",
    "Profile Card": "Profile Card",
    "Personal Information": "Personal Information",
    "Mail Settings": "Mail Settings",
    "Password Change": "Password Change",
    "Change Password": "Change Password",
    "Old Password": "Old Password",
    "New Password": "New Password",
    "Repeat New Password": "Repeat New Password",
    "Full Name": "Full Name",
    "Avatar": "Avatar",
    "Upload": "Upload",
    "Change Email": "Change Email",
    "New Email": "New Email",
    "Allowed file types:  png, jpg, jpeg.": "Allowed file types: png, jpg, jpeg.",
    "You don't have an account": "You don't have an account",
    "Log in": "Log in",
    "Please enter your details": "Please enter your details",
    "Remember Me": "Remember Me",
    "Reset password": "Reset password",
    "Lets get started": "Lets get started",
    "Company Name": "Company Name",
    "I have read the": "I have read the",
    "Terms and Conditions": "Terms and Conditions",
    "Already have an account": "Already have an account",
    "Color Scheme": "Color Scheme",
    "Menu Type": "{Menu} Type",
    "Menu Theme": "{Menu} Theme",
    "Slim +": "Slim +",
    "Primary Color": "Primary Color",
    "Input Style": "Input Style",
    "Ripple Effect": "Ripple Effect",
    "Personal settings": "Personal settings",
    "Company settings": "Company settings",
    "Integration and other settings": "Integration and other settings",
    "Safe logout": "Safe logout",
    "There is nothing here": "There is nothing here",
    "Go to Home": "Go to Home",
    "Change Language": "Change Language",
    "Forgot Password": "Forgot Password",
    "Enter your email to reset your password": "Enter your email to reset your password",
    "Reset Password": "Reset Password",
    "Remember your password?": "Remember your password?",
    "Cannot access to server": "Cannot access to server",
    "Please confirm terms and conditions": "Please confirm terms and conditions",
    "Check validation errors": "Check validation errors",
    "Welcome": "Welcome",
    "Dashboard": "Dashboard",
    "Widget": "Widget",
    "Oops": "Oops",
    "Logout": "Logout",
    "Search": "Search",
    "Profile": "Profile",
    "Outlined": "Outlined",
    "Filled": "Filled",
    "Light": "Light",
    "Dark": "Dark",
    "Dim": "Dim",
    "Transparent": "Transparent",
    "Static": "Static",
    "Overlay": "Overlay",
    "Slim": "Slim",
    "Reveal": "Reveal",
    "Drawer": "Drawer",
    "Horizontal": "Horizontal",
    "Scale": "Scale",
    "Themes": "Themes",
    "Password": "Password",
    "Register": "Register",
    "Menu": "Menu",
    "message": {
        "hello": "hello world!"
    },
    vueLocale: {
        "startsWith": "Starts with",
        "contains": "Contains",
        "notContains": "Not contains",
        "endsWith": "Ends with",
        "equals": "Equals",
        "notEquals": "Not equals",
        "noFilter": "No Filter",
        "filter": "Filter",
        "lt": "Less than",
        "lte": "Less than or equal to",
        "gt": "Greater than",
        "gte": "Greater than or equal to",
        "dateIs": "Date is",
        "dateIsNot": "Date is not",
        "dateBefore": "Date is before",
        "dateAfter": "Date is after",
        "custom": "Custom",
        "clear": "Clear",
        "apply": "Apply",
        "matchAll": "Match All",
        "matchAny": "Match Any",
        "addRule": "Add Rule",
        "removeRule": "Remove Rule",
        "accept": "Yes",
        "reject": "No",
        "choose": "Choose",
        "upload": "Upload",
        "cancel": "Cancel",
        "completed": "Completed",
        "pending": "Pending",
        "fileSizeTypes": ["B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"],
        "dayNames": ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        "dayNamesShort": ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        "dayNamesMin": ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
        "monthNames": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        "monthNamesShort": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        "chooseYear": "Choose Year",
        "chooseMonth": "Choose Month",
        "chooseDate": "Choose Date",
        "prevDecade": "Previous Decade",
        "nextDecade": "Next Decade",
        "prevYear": "Previous Year",
        "nextYear": "Next Year",
        "prevMonth": "Previous Month",
        "nextMonth": "Next Month",
        "prevHour": "Previous Hour",
        "nextHour": "Next Hour",
        "prevMinute": "Previous Minute",
        "nextMinute": "Next Minute",
        "prevSecond": "Previous Second",
        "nextSecond": "Next Second",
        "am": "AM",
        "pm": "PM",
        "today": "Today",
        "now": "Now",
        "weekHeader": "Wk",
        "firstDayOfWeek": 0,
        "showMonthAfterYear": false,
        "dateFormat": "mm/dd/yy",
        "weak": "Weak",
        "medium": "Medium",
        "strong": "Strong",
        "passwordPrompt": "Enter a password",
        "emptyFilterMessage": "No results found",
        "searchMessage": "{0} results are available",
        "selectionMessage": "{0} items selected",
        "emptySelectionMessage": "No selected item",
        "emptySearchMessage": "No results found",
        "emptyMessage": "No available options",
        "aria": {
            "trueLabel": "True",
            "falseLabel": "False",
            "nullLabel": "Not Selected",
            "star": "1 star",
            "stars": "{star} stars",
            "selectAll": "All items selected",
            "unselectAll": "All items unselected",
            "close": "Close",
            "previous": "Previous",
            "next": "Next",
            "navigation": "Navigation",
            "scrollTop": "Scroll Top",
            "moveTop": "Move Top",
            "moveUp": "Move Up",
            "moveDown": "Move Down",
            "moveBottom": "Move Bottom",
            "moveToTarget": "Move to Target",
            "moveToSource": "Move to Source",
            "moveAllToTarget": "Move All to Target",
            "moveAllToSource": "Move All to Source",
            "pageLabel": "Page {page}",
            "firstPageLabel": "First Page",
            "lastPageLabel": "Last Page",
            "nextPageLabel": "Next Page",
            "previousPageLabel": "Previous Page",
            "rowsPerPageLabel": "Rows per page",
            "jumpToPageDropdownLabel": "Jump to Page Dropdown",
            "jumpToPageInputLabel": "Jump to Page Input",
            "selectRow": "Row Selected",
            "unselectRow": "Row Unselected",
            "expandRow": "Row Expanded",
            "collapseRow": "Row Collapsed",
            "showFilterMenu": "Show Filter Menu",
            "hideFilterMenu": "Hide Filter Menu",
            "filterOperator": "Filter Operator",
            "filterConstraint": "Filter Constraint",
            "editRow": "Edit Row",
            "saveEdit": "Save Edit",
            "cancelEdit": "Cancel Edit",
            "listView": "List View",
            "gridView": "Grid View",
            "slide": "Slide",
            "slideNumber": "{slideNumber}",
            "zoomImage": "Zoom Image",
            "zoomIn": "Zoom In",
            "zoomOut": "Zoom Out",
            "rotateRight": "Rotate Right",
            "rotateLeft": "Rotate Left"
        }
    }
}

export default en;
