const tr = {
    "yyyymmmdd": "dd MMM yyyy",
    "yyyymmddhhmm": "dd/MM/yyyy hh:mm",
    "yyyymmmddhhmm": "dd MMM yyyy hh:mm",
    "yyyymmddhhmmss": "dd/MM/yyyy hh:mm:ss",
    "yyyy": "yyyy",
    "mmm": "MMM",
    "ddd": "ddd",
    "yyyymm": "yyyy/MM",
    "yyyymmm": "yyyy MMM",
    "mmdd": "MM/dd",
    "mmmdd": "MMM dd",
    "yyyymmdd": "dd/MM/yyyy",
    "NoInfo": "Bilgi Yok",
    "Production Status": "Üretim Durumu",
    "WaitingForSkeleton": "İskelet Bekliyor",
    "SkeletonReady": "İskeleti Hazır",
    "WaitingForFabric": "Kumaş Bekliyor",
    "FabricReady": "Kumaş Hazır",
    "FabricCutting": "Kumaş Kesimde",
    "FabricSewing": "Kumaş Dikimde",
    "SentToCapitone": "Kapitoneye Gönderildi",
    "ReceivedFromCapitone": "Kapitondan Geldi",
    "SentToProduction": "Üretime Verildi",
    "Produced": "Üretildi",
    "Packaged": "Paketlendi",
    "InWarehouse": "Depoda",
    "Completed": "Tamamlandı",
    "Watermark Is Active": "Resimlere Filigran Ekle",
    "Ongoing": "Devam Edenler",
    "Shipment": "Sevkiyat",
    "All products have the same status. Should the status of the main order also change?": "Tüm ürünler aynı statüde. Ana siparişin statüsü de değişsin mi?",
    "This accounts balance not equal zero. Can not archived": "Bu carinin bakiyesi sıfır değil, arşivlenemez. Önce bakiyeyi sıfırlayın.",
    "This accounts balance not equal zero. Can not delete": "Bu carinin bakiyesi sıfır değil, silinemez. Önce bakiyeyi sıfırlayın.",
    "Sales Consultant": "Satış Danışmanı",
    "Sales Consultant Phone": "Satış Danışmanı Tel",
    "Clone Product": "Ürünü Klonla",
    "Repeat Order": "Siparişi Tekrarla",
    "Are you sure you want to change archive status?": "Arşiv durumunu değiştirmek istediğinize emin misiniz?",
    "Remove Unit Price From Customer Order": "Birim Fiyatlarını Müşteri Siparişinden Kaldır",
    "Sms Provider": "Sms Sağlayıcı",
    "OtherUsersOrdersView": "Diğer Kullanıcıların Oluşturduğu Siparişleri Görme",
    "Has Production Unit": "Üretim Biriminiz Var mı?",
    "Productor User": "Üretimi Yapan Usta",
    "Production Start Date": "Üretim Başlangıç Tarihi",
    "Waiting Amount": "Ödeme Bekleyen Tutar",
    "Add Price To Supplier Order": "Sipariş Mailinde Üreticilere Alış Fiyatını da Gönder ",
    "Send Customer Order Created Sms": "Sipariş Oluştuğunda Müşteriye SMS At",
    "Send Supplier For Order Sms": "Sipariş Oluştuğunda Üreticiye SMS At",
    "Deal Accepted Sms": "Teklif Kabul Olduğunda SMS Al",
    "Create Deal Sms": "Teklif Oluştuğunda Müşteriye SMS At",
    "Edit Email Notif": "Mail Bildirimlerini Düzenle",
    "Edit SMS Notif": "SMS Bildirimlerini Düzenle",

    "Send Customer Order Created Mail": "Sipariş Oluştuğunda Müşteriye Email At",
    "Send Supplier For Order Mail": "Sipariş Oluştuğunda Üreticiye Email At",
    "Deal Accepted Mail": "Teklif Kabul Olduğunda Email Al",
    "Create Deal Mail": "Teklif Oluştuğunda Müşteriye Email At",

    "Abroad Sales Contract Text": "Yurtdışı Satış Sözleşmesi",
    "Corporate Representative": "Kurum Yetkilisi İsmi",
    "Personal": "Şahıs",
    "Corporate": "Kurum",
    "Entity Category": "Cari Türü",
    "Goverment Identity Number": "TCKN / VKN",
    "Show Data": "Veriyi Göster",
    "P.U.P.": "A.B.F.",
    "Ongoing Orders": "Devam Eden Siparişler",
    "Completed Orders": "Tamamlanan Siparişler",
    "Order Track": "Sipariş Takip",
    "Notification Detail": "Bildirim Detayı",
    "Enable Ssl": "SSL Aktif",
    "View": "Görüntüle",
    "Cash Statement": "Kasa Ekstresi",
    "Edit Cash": "Kasayı Düzenle",
    "View Statement": "Ekstre Gözlem",
    "Order QR Code": "Sipariş QR Kodu",
    "Up": "Zam",
    "Down": "İndirim",
    "Price Change Ways": "Fiyat Değişim Yöntemi",
    "Price Change Type": "Fiyat Değişim Tipi",
    "Are you sure you want to resend notificaiton?": "Bildirimi yeniden göndermek istediğinizden emin misiniz?",
    "Sms Sended Successfully": "SMS başarıyla gönderildi",
    "Mail Sended Successfully": "E-posta başarıyla gönderildi",
    "Resend Notif": "Bildirimi yeniden gönder",
    "January": "Ocak",
    "February": "Şubat",
    "March": "Mart",
    "April": "Nisan",
    "May": "Mayıs",
    "June": "Haziran",
    "July": "Temmuz",
    "August": "Ağustos",
    "September": "Eylül",
    "October": "Ekim",
    "November": "Kasım",
    "December": "Aralık",
    "Production Confirm Link": "Üretim Onay Formu Linki",
    "Not Completed": "Tamamlamadınız",
    "Subject": "Başlık",
    "Send Date": "Gönderim Tarihi",
    "Result Message": "Sonuç Mesajı",
    "Is Successful": "Durum",
    "Notification Way": "Bildirim Tipi",
    "Receiver": "Alıcı",
    "Mail Sms Report": "Mail/Sms Raporu",
    "View Order": "Siparişi Görüntüle",
    "Save Price": "Fiyatı Kaydet",
    "Recalculate prices": "Fiyatları yeniden hesapla",
    "ProductUnit": "Üretim Birimi",
    "ProductView": "Ürün Görüntüleme",
    "OfferView": "Teklif Görüntüleme",
    "OrderView": "Sipariş Görüntüleme",
    "OrderEdit": "Sipariş Düzenleme",
    "OrderPriceView": "Sipariş Fiyatı Görüntüleme",
    "OrderStatusChange": "Sipariş Durumu Değiştirme",
    "FinancialItemManagement": "Finansal Kalem Yönetimi",
    "FinancialItemReportView": "Finansal Kalem Raporu Görüntüleme",
    "CashAccountView": "Kasa Hesabı Görüntüleme",
    "CashAccountEdit": "Kasa Hesabı Düzenleme",
    "CashAccountStatementView": "Kasa Hesabı Ekstresi Görüntüleme",
    "CashTransactionView": "Kasa Hareketleri Görüntüleme",
    "CashTransactionEdit": "Kasa Hareketi Düzenleme",
    "FinancialTransactionView": "Ticari Hareketleri Görüntüleme",
    "FinancialTransactionEdit": "Ticari Hareket Düzenleme",
    "FinancialAccountView": "Cari Hesapları Görüntüleme",
    "FinancialAccountBalanceView": "Cari Hesap Bakiyesi Görüntüleme",
    "FinancialAccountEdit": "Cari Hesap Düzenleme",
    "FinancialAccountStatementView": "Cari Hesap Ekstresi Görüntüleme",
    "CompanySettingsManagement": "Şirket Ayarları Yönetimi",
    "UserView": "Kullanıcı Görüntüleme",
    "UserEdit": "Kullanıcı Düzenleme",
    "RoleManagement": "Rol Yönetimi",
    "SmsEmailView": "SMS/Email Görüntüleme",
    "Bank Account Iban": "Banka Hesabı IBAN No",
    "Bank Account No": "Banka Hesap No",
    "Bank Branch No": "Banka Şube No",
    "Load From Gallery": "Galeriden Yükle",
    "Save Product": "Ürünü Kaydet",
    "Show All Products": "Tüm ürünleri göster",
    "Show Only Parent Products": "Sadece ana ürünleri göster",
    "Back": "Geri",
    "Archived successfully": "Başarıyla arşivlendi, tüm marketlerden silinecek",
    "Summary": "Özet",
    "Account Statement": "Hesap Ekstresi",
    "Total Waiting Credit": "Gecikmiş Alacak",
    "Total Waiting Debt": "Gecikmiş Borç",
    "Waiting Payment Balance": "Ödeme Bekleyen Bakiye",
    "Pay": "Ödeme Yap",
    "Get Paid": "Ödeme AL",
    "Earn": "Kazanç",
    "Customer Debt": "Müşteri Borcu",
    "Receiver Financial Account": "Alıcı Cari Hesap",
    "Financial Account Offset": "Cari Mahsuplaşma",
    "Create Credit": "Alacak Oluştur",
    "Create Debt": "Borç Oluştur",
    "Search Cash": "Kasa Ara",
    "Search Product to Add Module": "Modül Eklemek İçin Ürün Ara",
    "Financial Account or Financial Item is required": "Cari Hesap veya Kalem zorunludur",
    "Product Image Width x Height": "Ürün Resim Genişliği x Yüksekliği",
    "Product Settings": "Ürün Ayarları",
    "Product Image Width": "Ürün Resim Genişliği",
    "Product Image Height": "Ürün Resim Yüksekliği",
    "Are you sure you want to delete?": "Silmek istediğinizden emin misiniz?",
    "Are you sure you want to add to archive?": "Arşive taşımak istediğinizden emin misiniz?",
    'Are you sure you want to change status?': 'Durumu değiştirmek istediğinizden emin misiniz? Tüm ürünlerin sipariş durumları değişecektir.',
    "Confirmation": "Onay",
    "Cancel": "İptal",
    "Confirm": "Onayla",
    "Change Language": "Dili Değiştir",
    "Contact": "İletişim",
    "Address": "Adres",
    "Full Licence": "Tam Lisans",
    "Extended Licence": "Genişletilmiş Lisans",
    "Basic License": "Temel Lisans",
    "How to Move Your Store to the E-commerce World": "Mağazanızı E-ticaret Dünyasına Nasıl Taşırsınız",
    "All you need to do is contact us, you are ready in just 10 minutes": "Yapmanız gereken tek şey bizimle iletişime geçmek, yalnızca 10 dakikada hazırsınız",
    "Try for free": "Ücretsiz deneyin",
    "Let's digitalize your store together": "Mağazanızı birlikte dijitalleştirelim",
    "Leave the hard work to , to reduce the workload of your employees by 70% and use them more effectively.": "Zor işleri bize bırakın, çalışanlarınızın iş yükünü %70 oranında azaltın ve onları daha etkili kullanın.",
    "Simple Order Create": "Basit Sipariş Oluşturma",
    "Simple Accounting": "Basit Muhasebe",
    "Pricing Plans": "Fiyatlandırma",
    "Choose a plan that works best for you and your team.": "Sizin ve ekibiniz için en iyi planı seçin.",
    "Your Software": "Sizin Yazılımınız",
    "Your software that provides solutions to your specific needs. Sign up now and get one month free": "Özel ihtiyaçlarınıza çözüm sunan ve sizinle büyüyen yazılım. Şimdi kaydolun ve bir ay ücretsiz deneyin",
    "Always up to date": "Her zaman güncel",
    "Fast": "Hızlı",
    "Easy": "Kolay",
    "Register Now": "Şimdi Kaydol",
    "Home": "Anasayfa",
    "Apps": "Uygulama",
    "Pricing": "Fiyatlandırma",
    "Features": "Özellikler",
    "Log in": "Giriş Yap",
    "Register Free": "Ücretsiz Kaydol",
    "10 admin account": "10 yönetici hesabı",
    "1 admin account": "1 yönetici hesabı",
    "Unlimited User Accounts": "Sınırsız Kullanıcı Hesabı",
    "Easy Product Management": "Kolay Ürün Yönetimi",
    "E-commerce Integration": "E-ticaret Entegrasyonu",
    "SMS/Email Integration": "SMS/Email Entegrasyonu",
    "Bulk Price Update": "Toplu Fiyat Güncelleme",
    "Product Sales and Tracking": "Ürün Satışı ve Takibi",
    "Order Proposal Preparation": "Sipariş Teklifi Hazırlama",
    "Easy Basic Accounting": "Kolay Temel Muhasebe",
    "Customer/Producer Debt Tracking": "Müşteri/Üretici Borç Takibi",
    "Profit/Loss Status Graphs": "Kar/Zarar Durum Grafikleri",
    "Shipping Setup Price Tracking": "Nakliye Kurulum Fiyat Takibi",
    "Shipping Tracking": "Nakliye Takibi",
    "Automate Shipping and Setup Costs": "Müşteri konumu bazlı nakliye ve kurulum fiyatlarını otomatik hesaplatarak sipariş anında hataların önüne geçebilir ve zamandan tasarruf edebilirsiniz.",
    "Theme": "Tema",
    "Customize Your Theme": "Dilediğiniz tema ayarını yaparak istediğiniz görsellikte sistemi kullanmaya devam edebilirsiniz.",
    "Mobile": "Mobil",
    "No Installation Required": "Sistemimiz hiçbir kurulum gerektirmez ve dilediğiniz her cihazdan anında erişim sağlayabilirsiniz.",
    "Domain Management": "Alan Adı Yönetimi",
    "Store Your Domain": "Alan Adınızı kendi sunucularınızda ya da Mobitolya'da saklayın.",
    "E Commerce Integration": "E-ticaret Entegrasyonu",
    "Instant Integration With E Commerce Platforms": "Woo-commerce, Trendyol gibi pek çok e-ticaret ortamı ile anında entegrasyon.",
    "Sales": "Satış",
    "Manage Your Products From A Single Panel": "Ürünlerinizi, ürün fiyatlarını ve satışlarınızı tek bir panelden yönetebilirsiniz.",
    "Sms/Mail Integration": "Sms/Mail Entegrasyonu",
    "Send Special Offers To Your Customers": "Müşterilerinize özel teklifler gönderin ve pek çok işlem için sms/mail entegrasyonu.",
    "Maintenance and Security": "Bakım ve Güvenlik",
    "Your Data Is Stored Securely": "Verileriniz şifreli şekilde saklanarak güvende ve her hafta düzenli yedekleme işlemi yapılmaktadır.",
    "Complete & New": "Tamamla & Yeni",
    "Save & New": "Kaydet & Yeni",
    "Bulk Price Update": "Toplu Fiyat Güncelleme",
    "Fast Price Update": "Hızlı Fiyat Güncelleme",
    "Last Update Date": "Son Güncelleme Tarihi",
    "Draft": "Taslak",
    "TransferCurrencyExchangeDescription": "İki hesap arasındaki döviz kuru farklı olduğundan,karşı hesaba geçecek miktarı manuel giriniz. eğer girmezseniz güncel kurdan çevrim yapılacaktır.",
    "Realized Target Amount": "Gerçekleşen Hedef Tutarı",
    "Completed successfully": "Başarıyla tamamlandı",
    "Collection from Customer": "Müşteriden Tahsilat",
    "Invalid credentials": "Geçersiz kimlik bilgileri",
    "Notification Phone Numbers": "Bildirim Telefon Numaraları",
    "Notification Emails": "Bildirim E-postaları",
    "Sales Channels": "Satış Kanalları",
    "Add Sales Channel": "Satış Kanalı Ekle",
    "Share Statement": "Hesap Özetini Paylaş",
    "Share": "Paylaş",
    "Download To Pdf": "Pdf olarak indir",
    "Filter For Date Range": "Tarih Aralığına Göre Filtrele",
    "Account Transactions": "Hesap Hareketleri",
    "Statement created succesfuly": "Hesap özeti başarıyla oluşturuldu",
    "Total Estimated Earn": "Toplam Tahmini Kazanç",
    "Total Cost": "Toplam Maliyet",
    "Total Selling Price": "Toplam Satış Fiyatı",
    "Offer Status": "Teklif Durumu",
    "View Count": "Görüntülenme Sayısı",
    "Complete Transfer": "Transferi Tamamla",
    "Debt + Credit": "Borç + Alacak",
    "Total Credit": "Toplam Alacak",
    "Total Debt": "Toplam Borç",
    "Profit Percentage": "Kar Yüzdesi",
    "Discount Percentage": "İndirim Yüzdesi",
    "Logo URL": "Logo URL",
    "Phone Numbers": "Telefon Numaraları",
    "Account Type": "Hesap Türü",
    "Email Adresses": "E-posta Adresleri",
    "Add Financial Account": "Cari Hesap Ekle",
    "Freight": "Navlun",
    "Package Quantity": "Paket Miktarı",
    "Cubic Meter": "Metreküp",
    "Only Sell On Stock": "Sadece Stoktan Satış",
    "Is Visible On Market": "Markette Görünür mü",
    "There is no detail": "Detay yok",
    "transportationCode_info": 'Toplu sevkiyatların takibi için aynı sevkiyatta gidecek siparişlere aynı kodu verin; Boş bırakılırsa müşteri ve teslimat tarihi bazlı otomatik kod üretilir',
    "Transportation Code": "Sevkiyat Kodu",
    "Add Transportation": "Nakliye Hizmeti Ekle",
    "Add Installation": "Kurulum Hizmeti Ekle",
    "Service Type": "Hizmet Türü",
    "Installation": "Montaj",
    "Transportation": "Nakliye",
    "Service": "Hizmet",
    "Maintenance": "SSH",
    "Other": "Diğer",
    "Free": "Ücretsiz",
    "Total Earn": "Toplam Kazanç",
    "Save Cart": "Sepeti Kaydet",
    "Selling Unit Price": "Satış Birim Fiyatı",
    "Purchase Unit Price": "Alış Birim Fiyatı",
    "Service/Product Provider": "Ürün/Hizmet Sağlayıcı",
    "Valid Country": "Geçerli Olduğu Ülke",
    "Valid Province": "Geçerli Olduğu İl",
    "New Offer Demanded Successfuly": "Yeni Teklif Talebi Başarıyla Oluşturuldu",
    "Offer Rejected Successfuly": "Teklif Başarıyla Reddedildi",
    "Offer Accepted Successfuly": "Teklif Başarıyla Kabul Edildi",
    "Copy to link": "Linki Kopyala",
    "View offer": "Teklifi Görüntüle",
    "Share to whatsapp": "Whatsapp'ta paylaş",
    'offerMessage': '/%23/Public/CustomerDeal/{code} adresinde {companyName} olarak seçili ürünler için size harika bir teklifimiz var, teklifi görmek için linke tıklayın.',
    "Deleted successfully": "Başarıyla silindi",
    "Created successfully": "Başarıyla oluşturuldu",
    "Updated successfully": "Başarıyla güncellendi",
    "Quantity": "Adet",
    "Unit Price": "Birim Fiyatı",
    "Order Status": "Sipariş Durumu",
    "Color": "Renk",
    "Product Attribute": "Ürün Özellikleri",
    "Attribute List": "Özellik Listesi",
    "Syncronize to WooCommerce": "WooCommerce ile Senkronize Et",
    "Excel Export": "Excel Dışa Aktar",
    "Show Archive": "Arşivi Göster",
    "Hide Archive": "Arşivi Gizle",
    "Unarchive": "Arşivden Çıkar",
    "Add to archive": "Arşive taşı",
    "Financila Accounts": "Cari Hesaplar",
    "Financial Account Type": "Cari Hesap Türü",
    "Balance": "Bakiye",
    "Code": "Kod",
    "Delivery Form": "Teslimat Formu",
    "Contract Form": "Sözleşme Formu",
    "Production Slip": "Üretim Fişi",
    "Offer": "Teklif",
    'Create Offer': 'Teklif Oluştur',
    'Edit Offer': 'Teklifi Düzenle',
    "Expiry Date": "Son Geçerlilik Tarihi",
    "Total Offer Price": "Toplam Teklif Fiyatı",
    "Table": "Tablo",
    "Detailed View": "Detaylı Görünüm",
    "Simple View": "Basit Görünüm",
    "Save Transaction": "İşlemi Kaydet",
    "Owe someone": "Borçlan",
    "Be a creditor": "Borçlandır",
    "Cash Account": "Kasa Hesabı",
    "Cash Transactions": "Nakit Akışı",
    "Bank Name": "Banka Adı",
    "Initial Balance": "Başlangıç Bakiyesi",
    'Create New Cash Account': 'Yeni Kasa Hesabı Oluştur',
    'Create Account': 'Hesap Oluştur',
    'Close': 'Kapat',
    'Save Account': 'Hesabı Kaydet',
    'Account Entry': 'Hesaba Giriş',
    'Account Exit': 'Hesaptan Çıkış',
    'Transfer to Account': 'Hesaba Transfer',
    'Collection from Receivable': 'Cariden Tahsilat',
    'Payment to Payable': 'Cariye Ödeme',
    "Debit": "Borç",
    "Credit": "Alacak",
    "Due Date": "Son Ödeme Tarihi",
    "Transaction Type": "İşlem Tipi",
    "Attributes Supported by Category": "Kategori Tarafından Desteklenen Özellikler",
    "Create New Attribute": "Yeni Özellik Oluştur",
    "Option Name": "Seçenek Adı",
    "Add new {item} option": "Yeni {item} Seçeneği Ekle",
    "Service Name": "Hizmet Adı",
    "Order": "Sipariş",
    "Product / Service": "Ürün / Hizmet",
    "Attributes": "Özellikler",
    "Services": "Hizmetler",
    "Service": "Hizmet",
    "Destination Account": "Hedef Hesap",
    "Create New Financial Item": "Yeni Kalem Oluştur",
    "Parent Financial Item": "Üst Kalem",
    "Financial Revenue Item List": "Gelir Kalemleri",
    "Financial Expense Item List": "Gider Kalemleri",
    "Transaction Date": "İşlem Tarihi",
    "Financial Account": "Cari Hesap",
    "Financial Item": "Kalem",
    "Amount": "Tutar",
    'Category List': 'Kategori Listesi',
    'Create New Category': 'Yeni Kategori Oluştur',
    'Edit Category': 'Kategoriyi Düzenle',
    'Parent Category': 'Üst Kategori',
    'Company Settings': 'Şirket Ayarları',
    'General Settings': 'Genel Ayarlar',
    'Company Name': 'Şirket Adı',
    'Tax Identification Number': 'Vergi Kimlik Numarası',
    'Logo Url': 'Logo URL',
    'Web Site Url': 'Web Sitesi URL',
    'Redirection Url': 'Yönlendirme URL',
    'Sales Advertisement Settings': 'Satış Reklam Ayarları',
    'Social Media': 'Sosyal Medya',
    'Sales Consultant Phone Number 1': 'Satış Danışmanı Telefon Numarası 1',
    'Sales Consultant Phone Number 2': 'Satış Danışmanı Telefon Numarası 2',
    'Transporting Phone Number': 'Nakliye Telefon Numarası',
    'SSH Phone Number': 'SSH Telefon Numarası',
    'SSH Email': 'SSH E-posta',
    'Sales Contract Text': 'Satış Sözleşmesi Metni',
    'Subscription Information': 'Abonelik Bilgileri',
    'Subscription Type': 'Abonelik Tipi',
    'Subscription End Date': 'Abonelik Bitiş Tarihi',
    'Financial Settings': 'Finansal Ayarlar',
    'Main Currency Type': 'Ana Para Birimi',
    'Default Discount Percentage': 'Varsayılan İndirim Yüzdesi',
    'Default Profit Percentage': 'Varsayılan Kar Yüzdesi',
    'Sales Colsultant Max Discount Percentage': 'Satış Danışmanı Maksimum İndirim Yüzdesi',
    'Email Integration': 'E-posta Entegrasyonu',
    'Sms Integration': 'SMS Entegrasyonu',
    'User Name': 'Kullanıcı Adı',
    'Password': 'Şifre',
    'Sender Name': 'Gönderici Adı',
    'Smtp Client': 'SMTP İstemcisi',
    'Port': 'Port',
    'Api Url': 'API URL',
    'Key': 'Anahtar',
    'Secret': 'Gizli Anahtar',
    'Coming Soon': 'Yakında',
    'Address Information': 'Adres Bilgileri',
    'Country': 'Ülke',
    'Province': 'İl',
    'District': 'İlçe',
    'Address Detail': 'Adres Detayı',
    "Address Information": "Adres Bilgisi",
    "Country": "Ülke",
    "Province": "İl",
    "District": "İlçe",
    "Address Detail": "Adres Detayı",
    "Subtotal": "Ara Toplam",
    'Details': 'Detaylar',
    'Description': 'Açıklama',
    'Order Code': 'Sipariş Kodu',
    'Process Tracker User': 'Süreci Takip Eden Çalışan',
    'Sales Channel': 'Satış Kanalı',
    "Customer Id": "Müşteri",
    'Create Order': 'Sipariş Oluştur',
    'Edit Order': 'Siparişi Düzenle',
    'Save': 'Kaydet',
    'Customer Information': 'Müşteri Bilgileri',
    'Shipping': 'Gönderim',
    'Order Date': 'Sipariş Tarihi',
    'Estimated Delivery Date': 'Teslimat Tarihi',
    'Estimated Dead Line Date': 'Termin Tarihi',
    'Is Abroad': 'Yurt Dışı mı?',
    'Return to Cart': 'Sepete Dön',
    'Continue to Shipping': 'Gönderime Devam Et',
    'Customer Cart': 'Müşteri Sepeti',
    'Search Product to Add Cart': 'Sepete Eklemek İçin Ürün Ara',
    'Cart is empty yet': 'Sepet henüz boş',
    'Please search product to add to cart from up side': 'Lütfen yukarıdan sepete eklemek için ürün arayın',
    'Service': 'Hizmet',
    'Product': 'Ürün',
    'Enter Details': 'Detayları Girin',
    'Currency Type': 'Para Birimi Tipi',
    'Total': 'Toplam',
    'No additional duties or taxes.': 'Ek vergi veya harç yok.',
    "Click to edit": "Düzenlemek için tıklayın",
    "Images": "Resimler",
    "empty_text": "",
    "Add": "Ekle",
    "Composite Product": "Modül Ürün",
    "There is no composite product, add from right up": "Bu ürüne ait modül tanımlanmadı, üst kısımdan ekleyin",
    "This field shows the percentage discount at which you purchased the product.": "Bu alan, ürünü yüzde kaç indirimli aldığınızı gösterir.",
    "Composite Products": "Modüller",
    "Selling": "Satış",
    "Categories": "Kategoriler",
    "Set the percentage profit for this product. If no value is entered, the default rate is shown.": "Bu ürünün yüzde kaç karla satılacağını belirleyin. Bir değer girmezseniz varsayılan oran gösterilir.",
    "Default Sales Quantity": "Varsayılan Satış Miktarı",
    "Add Service": "Hizmet Ekle",
    "Add Product": "Ürün Ekle",
    "Edit Service": "Hizmeti Düzenle",
    "Edit Product": "Ürünü Düzenle",
    "Save": "Kaydet",
    "Name On Sale": "Satıştaki Adı",
    "Selling Price": "Satış Fiyatı",
    "Promotional Price": "Promosyon Fiyatı",
    "Product Code": "Ürün Kodu",
    "Currency Type": "Para Birimi Tipi",
    "Is a Service": "Bu bir hizmet",
    "Own Provided Service": "Kendi sağladığımız hizmet",
    "Own Production": "Kendi üretimimiz",
    "Operation": "Operasyon",
    "Production": "Üretim",
    "Supplier": "Tedarikçi/Üretici",
    "Name In Production": "Üretimdeki Adı",
    "Purchase List Price": "Liste Fiyatı",
    "Purchase Price": "Alış Fiyatı",
    "Cost": "Maliyet",
    "Status": "Durum",
    "Tags": "Etiketler",
    "Category": "Kategori",
    "Discard": "Vazgeç",
    "Publish": "Yayınla",
    "Drop or select a cover image": "Resimleri sürükle bırak veya seç",
    "Percentage": "Yüzde",
    "Deposit": "Yatırma",
    "Withdrawal": "Çekme",
    "TRY": "TRY",
    "USD": "USD",
    "EUR": "EUR",
    "GBP": "GBP",
    "Pending": "Onay Bekliyor",
    "Ordered": "Sipariş Verildi",
    "Canceled": "İptal",
    "Preparing": "Hazırlanıyor",
    "Depot": "Depoda",
    "Transporting": "Nakliyede",
    "Completed": "Tamamlandı",
    "Refund": "İade",
    "Customer": "Müşteri",
    "Transporter": "Nakliyeci",
    "Textile": "Tekstil",
    "Other": "Diğer",
    "Expense": "Gider",
    "Revenue": "Gelir",
    "Debit": "Borç",
    "Credit": "Alacak",
    "WaitingToCustomer": "Müşteriden Cevap Bekleniyor",
    "Accepted": "Kabul Edildi",
    "Rejected": "Reddedildi",
    "Confirmed": "Onaylandı",
    "CustomerWaitingForNewOffer": "Müşteri Yeni Teklif Bekliyor",
    "Products": "Ürünler",
    "Deals": "Fırsatlar",
    "SellingOrders": "Satış Siparişleri",
    "BuyingOrders": "Alış Siparişleri",
    "Accounts": "Hesaplar",
    "Payments": "Ödemeler",
    "SupplierAccounting": "Tedarikçi/Üretici Muhasebesi",
    "CustomerAccounting": "Müşteri Muhasebesi",
    "Settings": "Ayarlar",
    "SmsEmail": "SMS/E-posta",
    "Active": "Aktif",
    "Passive": "Pasif",
    "None": "Hiçbiri",
    "Monthly": "Aylık",
    "Quarterly": "Üç Aylık",
    "Semiannually": "Yarı Yıllık",
    "Annually": "Yıllık",
    "None": "Hiçbiri",
    "OnlyIntegration": "Sadece Entegrasyon",
    "IntegrationAndSelling": "Entegrasyon ve Satış",
    "All": "Tümü",
    "Preparing": "Hazırlanıyor",
    "Producted": "Üretildi",
    "Canceled": "İptal",
    "Refund": "İade",
    "NotStarted": "Başlamadı",
    "InProgress": "Devam Ediyor",
    "Completed": "Tamamlandı",
    "Admin": "Yönetici",
    "CompanyManager": "Şirket Yöneticisi",
    "SalesConsultant": "Satış Danışmanı",
    "SupportUser": "Destek Kullanıcısı",
    "ShipmentUser": "Sevkiyat Kullanıcısı",
    "AccountingUser": "Muhasebe Kullanıcısı",
    "App": "Uygulama",
    "Home": "Ana Sayfa",
    "Products": "Ürünler",
    "Orders": "Siparişler",
    "Offers": "Teklifler",
    "Customer Orders": "Siparişler",
    "Supplier Orders": "Tedarik",
    "Invoices": "Faturalar",
    "Accounting": "Muhasebe",
    "Cashs": "Kasalar",
    "Financial Accounts": "Cariler",
    "Financial Items": "Kalemler",
    "Financial Transactions": "Ticari Hareketler",
    "Financial Plans": "Finansal Planlar",
    "System": "Sistem",
    "Company": "Şirket",
    "Users": "Kullanıcılar",
    "Roles": "Roller",
    "Product Name": "Ürün Adı",
    "Status": "Durum",
    "Manufacturer": "Üretici",
    "Stock Code": "Stok Kodu",
    "Stock Quantity": "Stok Adedi",
    "Product Purchase Price": "Ürün Alış Fiyatı",
    "Product Selling Price": "Ürün Satış Fiyatı",
    "Discounted Selling Price": "İndirimli Satış Fiyatı",
    "Last Update": "Son Güncelleme",
    "Actions": "İşlemler",
    "Filter": "Filtrele",
    "Profile successfully updated": "Profil başarıyla güncellendi",
    "Succeeded": "Başarılı",
    "Password successfully updated": "Şifre başarıyla güncellendi",
    "Password must be at least 6 characters long": "Şifre en az 6 karakter uzunluğunda olmalıdır",
    "New password repeat not equal to new password": "Yeni şifre tekrarı yeni şifre ile eşleşmiyor",
    "Admin": "Admin",
    "Error": "Hata",
    "Succeded": "Başarılı",
    "Email already using by another user": "E-posta zaten başka bir kullanıcı tarafından kullanılıyor,başka bir e-posta girin",
    "Enter a valid email address": "Geçerli bir e-posta adresi girin",
    "UserType": "Kullanıcı Türü",
    "{field} field is required": "{field} alanı zorunludur",
    "Options": "Seçenekler",
    "Filter Menu": "Filtre Menüsü",
    "Clear": "Temizle",
    "Create New": "Yeni Oluştur",
    "Keyword Search": "Anahtar Kelime Arama",
    "No data found": "Veri bulunamadı",
    "Loading data. Please wait": "Veriler yükleniyor. Lütfen bekleyin",
    "Create Date": "Oluşturma Tarihi",
    "{totalRecords} records found from {first} to {last}": "{'{'}totalRecords{'}'} kayıt bulundu, {'{'}first{'}'} ile {'{'}last{'}'} arasında",
    "Search by Name": "İsme göre ara",
    "Search by Email": "E-postaya göre ara",
    "dd/mm/yyyy": "gg/aa/yyyy",
    "Edit": "Düzenle",
    "Delete": "Sil",
    "Add User": "Kullanıcı Ekle",
    "Edit User": "Kullanıcı Düzenle",
    "General": "Genel",
    "Name": "İsim",
    "Users": "Kullanıcılar",
    "User": "Kullanıcı",
    "Phone Number": "Telefon Numarası",
    "User Type": "Kullanıcı Türü",
    "Profile Card": "Profil Kartı",
    "Personal Information": "Kişisel Bilgiler",
    "Mail Settings": "E-posta Ayarları",
    "Password Change": "Şifre Değiştir",
    "Change Password": "Şifre Değiştir",
    "Old Password": "Eski Şifre",
    "New Password": "Yeni Şifre",
    "Repeat New Password": "Yeni Şifreyi Tekrarla",
    "Personal Information": "Kişisel Bilgiler",
    "Full Name": "Ad Soyad",
    "Phone Number": "Telefon Numarası",
    "Avatar": "Profil Fotoğrafı",
    "Upload": "Yükle",
    "Change Email": "E-postayı Değiştir",
    "Save": "Kaydet",
    "Email": "E-posta",
    "New Email": "Yeni E-posta",
    "Delete": "Sil",
    "Allowed file types:  png, jpg, jpeg.": "İzin verilen dosya türleri: png, jpg, jpeg.",
    "You don't have an account": "Bir hesabınız yok mu",
    "Log in": "Giriş Yap",
    "Please enter your details": "Lütfen hesap bilgilerinizi girin",
    "Remember Me": "Beni Hatırla",
    "Reset password": "Şifremi unuttum",
    "Lets get started": "Hadi Başlayalım",
    "Company Name": "İşletme Adınız",
    "I have read the": "Okudum onaylıyorum",
    "Terms and Conditions": "Hüküm ve Koşullar",
    "Already have an account": "Zaten bir hesabınız var mı",
    "Color Scheme": "Renk Modu",
    "Menu Type": "{Menu} Tipi",
    "Menu Theme": "{Menu} Teması",
    "Slim +": "İnce +",
    "Primary Color": "Öncelikli Renk",
    "Input Style": "Giriş Stili",
    "Ripple Effect": "Dalga etkisi",
    "Personal settings": "Kişisel ayarlar",
    "Company settings": "İşletme ayarları",
    "Integration and other settings": "Entegrasyon ve diğer ayarlar",
    "Safe logout": "Güvenli çıkış",
    "There is nothing here": "Burda hiç birşey yok",
    "Go to Home": "Anasayfaya dön",
    "Change Language": "Dil Değiştir",
    "Forgot Password": "Şifremi Unuttum",
    "Enter your email to reset your password": "Şifrenizi sıfırlamak için e-posta adresinizi girin",
    "Reset Password": "Şifreyi Sıfırla",
    "Remember your password?": "Şifrenizi hatırlıyor musunuz?",
    "Cannot access to server": "Server'a erişilemiyor",
    "Please confirm terms and conditions": "Hüküm ve koşulları kabul edin",
    "Check validation errors": "Hatalı verileri kontrol edin",

    "CompanyManager": "Firma Yöneticisi",
    "SalesConsultant": "Satış Temsilcisi",
    "SupportUser": "SSH Sorumlusu",
    "ShipmentUser": "Nakliye Sorumlusu",
    "AccountingUser": "Muhasebe Sorumlusu",

    "Welcome": "Hoşgeldiniz",
    "Dashboard": "Panel",
    "Widget": "Araç",
    "App": "Uygulama",
    "Oops": "Hay Aksi",
    "Users": "Kullanıcılar",
    "Home": "Anasayfa",
    "Logout": "Çıkış",
    "Search": "Ara",
    "Profile": "Profil",
    "Outlined": "Çerçeveli",
    "Filled": "Dolgulu",
    "Light": "Açık",
    "Dark": "Koyu",
    "Dim": "Loş",
    "Transparent": "Şeffaf",
    "Static": "Sabit",
    "Overlay": "Kapalı",
    "Slim": "İnce",
    "Reveal": "Dar",
    "Drawer": "Çekmece",
    "Horizontal": "Yatay",
    "Scale": "Boyut",
    "Themes": "Temalar",
    "Password": "Şifre",
    "Register": "Kaydol",
    "Menu": "Menü",
    "message": {
        "hello": "Merhaba Dünya!"
    },
    vueLocale: {
        startsWith: 'Şununla başlar',
        contains: 'İçerir',
        notContains: 'İçermez',
        endsWith: 'Şununla biter',
        equals: 'Eşittir',
        notEquals: 'Eşit değil',
        noFilter: 'Filtre Yok',
        lt: 'Daha az',
        lte: 'Küçüktür veya eşittir',
        gt: 'Daha büyük',
        gte: 'Büyüktür veya eşittir',
        dateIs: 'Şu tarihdeki',
        dateIsNot: 'Şu tarih dışındaki',
        dateBefore: 'Şu tarihden öncesi',
        dateAfter: 'Şu tarihden sonrası',
        clear: 'Temizle',
        apply: 'Uygula',
        matchAll: 'Tümünü Eşleştir',
        matchAny: 'Herhangi birini eşleştir',
        addRule: 'Kural Ekle',
        removeRule: 'Kural Kaldır',
        accept: 'Evet',
        reject: 'Hayır',
        choose: 'Seç',
        upload: 'Yükle',
        cancel: 'İptal',
        completed: 'Tamamlandı',
        pending: 'Beklemede',
        dayNames: ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'],
        dayNamesShort: ['Paz', 'Pzt', 'Sa', 'Çar', 'Per', 'Cum', 'Cmt'],
        dayNamesMin: ['Pz', 'Pt', 'Sa', 'Çr', 'Pr', 'Cu', 'Ct'],
        monthNames: ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'],
        MonthNamesShort: ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'],
        selectYear: 'Yıl Seçin',
        selectMonth: 'Ay Seçin',
        chooseDate: 'Tarih Seç',
        prevDecade: 'Önceki On Yıl',
        nextDecade: 'Gelecek On Yıl',
        prevYear: 'Önceki Yıl',
        nextYear: 'Gelecek Yıl',
        prevMonth: 'Önceki Ay',
        nextMonth: 'Gelecek Ay',
        prevHour: 'Önceki Saat',
        nextHour: 'Sonraki Saat',
        prevMinute: 'Önceki Dakika',
        nextMinute: 'Sonraki Dakika',
        prevSecond: 'Önceki Saniye',
        nextSecond: 'Sonraki Saniye',
        am: 'öö',
        pm: 'ös',
        today: 'Bugün',
        weekHeader: 'Hafta',
        firstDayOfWeek: 1,
        dateFormat: 'dd/mm/yy',
        weak: 'Zayıf',
        medium: 'Orta',
        strong: 'Güçlü',
        passwordPrompt: 'Bir şifre girin',
        emptyFilterMessage: "Sonuç bulunamadı", // @deprecated Bunun yerine "emptySearchMessage" seçeneğini kullanın.
        searchMessage: '{0} sonuç mevcut',
        selectionMessage: '{0} öğe seçildi',
        emptySelectionMessage: 'Seçili öğe yok',
        emptySearchMessage: 'Sonuç bulunamadı',
        emptyMessage: 'Kullanılabilir seçenek yok',
        aria: {
            trueLabel: 'Doğru',
            falseLabel: 'Yanlış',
            nullLabel: 'Seçili Değil',
            star: '1 yıldız',
            stars: '{yıldız} yıldız',
            selectAll: 'Tüm öğeler seçildi',
            unselectAll: 'Tüm öğeler seçilmedi',
            close: 'Kapat',
            previous: 'Önceki',
            next: 'Sonraki',
            navigation: 'Navigasyon',
            scrollTop: 'Üstü Kaydır',
            moveTop: 'Üstü Taşı',
            moveUp: 'Yukarı Taşı',
            moveDown: 'Aşağı Taşı',
            moveBottom: 'Altı Taşı',
            moveToTarget: 'Hedefe Taşı',
            moveToSource: 'Kaynağa Taşı',
            moveAllToTarget: 'Tümünü Hedefe Taşı',
            moveAllToSource: 'Tümünü Kaynağa Taşı',
            pageLabel: '{page}',
            firstPageLabel: 'İlk Sayfa',
            lastPageLabel: 'Son Sayfa',
            nextPageLabel: 'Sonraki Sayfa',
            prevPageLabel: 'Önceki Sayfa',
            rowsPerPageLabel: 'Sayfa başına satır sayısı',
            jumpToPageDropdownLabel: 'Sayfa Açılır Menüsüne Atla',
            jumpToPageInputLabel: 'Sayfa Girişine Atla',
            selectRow: 'Satır Seçildi',
            unselectRow: 'Satır Seçimi Kaldırıldı',
            ExpandRow: 'Satır Genişletildi',
            crashRow: 'Satır Daraltıldı',
            showFilterMenu: 'Filtre Menüsünü Göster',
            hideFilterMenu: 'Filtre Menüsünü Gizle',
            filterOperator: 'Filtre Operatörü',
            filterConstraint: 'Filtre Kısıtlaması',
            editRow: 'Satır Düzenleme',
            saveEdit: 'Düzenlemeyi Kaydet',
            cancelEdit: 'Düzenlemeyi İptal Et',
            listView: 'Liste Görünümü',
            gridView: 'Kılavuz Görünümü',
            slayt: 'Slayt',
            slideNumber: '{slideNumber}',
            zoomImage: 'Görüntüyü yakınlaştır',
            zoomIn: 'Yakınlaştır',
            zoomOut: 'Uzaklaştır',
            rotateRight: 'Sağa Döndür',
            rotateLeft: 'Sola Döndür'
        }
    }
}

export default tr;